spring.application.name=order-service

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics